export const PARKING_LOADED = "Parking/PARKING_LOADED";
export const PARKING_ADDED = "Parking/PARKING_ADDED";
export const PARKING_DELETED = "Parking/PARKING_DELETED";
export const PARKING_UPDATED = "Parking/PARKING_UPDATED";
export const PARKING_FETCHED = "Parking/PARKING_FETCHED";
export const PARKING_ADDED_SUCCESS = "Parking/PARKING_ADDED_SUCCESS";